services:
  browser:
    image: ghcr.io/browserless/firefox
    environment:
      - CONCURRENT=10
      - TOKEN=6R0W53R135510
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: toor

  scrapyd:
    build:
      context: ./scrapyd
    
  app:
    build:
      context: ./app
    ports:
      - 8080:8080

  web_server:
    image: nginx:alpine
    volumes:
      - ./homepage.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "80:80"